[package]
name = "data_process"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0"
polars-lazy = { version = "0", features = ["regex"] }
ndarray = "0"
